// ==========================================================
// --- Generated Aura mascot dynamic audio lookup map -------
// --- DO NOT EDIT MANUALLY - Generated via script ---------
// ==========================================================

window.auraAudioMap = {
  "hinglish": {
    "sleepy_egg": "sleepy-egg/Yawn...-Raat-kaafi-ho-gayi-hai_-Sadness-Split-karte-karte-so-mat-jana_-__.opus",
    "cpu_panic": "cpu_panic/Oye! System statistics are sweating! Mere dimaag me fire lag gayi hai! 🥵🔥.opus",
    "ffmpeg_missing": "ffmpeg_missing/Oh no... Please install FFmpeg! Without it, I am nothing... 😭.opus",
    "settings_saved": "setting_saved/Settings and variables successfully updated! Let's go! 🚀.opus",
    "theme_pink": "theme_pink/Aww is pink matching my vibe today👉👈.opus",
    "theme_red": "theme_red/Why so red Angry ho kya 😡.opus",
    "theme_green": "theme_green/Green looks fresh ready to crush some bitrates 🍃.opus",
    "theme_white": "theme_white/White So blank add some colors to your life 🥱.opus",
    "theme_blue": "theme_blue/Classic blue. Back to focus and coding 💻.opus",
    "theme_purple": "theme_purple/Purple elegance. Let's think of some cool cuts 🔮.opus",
    "theme_yellow": "theme_yellow/A sunny theme! Exciting times ahead.opus",
    "theme_win98": "theme_win98/Windows 98 Classic Sab kuch retro gray ho gaya... feel safe 📺.opus",
    "theme_winxp": "theme_winxp/Luna theme activated Let's split video in XP style.opus",
    "theme_synth": "retro_synth/Retro sunset vibing... Let's warp time with neon 🌆💜.opus",
    "success_compress": "sucess_compress/Boom Heavy baggage successfully compressed into a compact file.opus",
    "success_split": "sucess_split/Cut clean Your memories have been successfully split.opus",
    "success_trim": "sucess_trim/Trim complete All unnecessary clutter has been cut away 🧼.opus",
    "success_rotate": "sucesss_rotate/Perspective rotated successfully Looks amazing from this side.opus",
    "success_audio": "sucess_audio/Audio successfully extracted Aura is vibing to these beats 🎧🎶.opus",
    "success_convert": "success_convert/Conversion success! Brand new format, same emotions!.opus",
    "success_subtitle": "success_subtitle/Subtitles burned in! Every single word now carries weight.opus",
    "success_speed": "success_speed/Speed Warp applied! Time dilation is complete.opus",
    "success_gif": "sucess_gif/Elite loop generated Go share this loop and spread the laughter 😂.opus",
    "success_merger": "success_merger/Videos merged! Your timelines are beautifully unified! 💖.opus",
    "success_stabilize": "success_stabilize/Motion vector stabilization algorithm applied. Frame variance close to 0..opus",
    "success_contact": "success_contact/Contact sheet created. A grid of screenshots to prove we actually did something.opus",
    "success_batch": "success_batch/Batch processing completed! Aura worked overtime, but we crushed it.opus",
    "interact_poke_annoyed": "interact_poke_annoyed/Active compiler thread interrupted. Restoring focus baseline 😤.opus",
    "interact_poke_angry": "interact_poke_angry/ENOUGH IS ENOUGH Bahut ho gaya ab.opus",
    "interact_staring": "interact_staring/STOP STARING AT ME! Apna kaam karo na!.opus",
    "interact_metrics_blush": "interact_metrics_blush/Oh, you like my performance stats 👉👈.opus",
    "interact_metrics_tickle": "interact_metrics_tickle/Ah Stop it, that tickles! It's just my CPU and GPU stats 🙈.opus",
    "interact_metrics_annoyed": "interact_metrics_annoyed/HEY Stop poking me and focus on your work 💢.opus",
    "interact_metrics_cry": "interact_metrics_cry/Please don't disturb me, main cry kar dungi abhi... 😭.opus",
    "interact_metrics_sulking": "interact_metrics_sulking/Ok, fine, jo karna hai karo... humph 🙄.opus",
    "interact_browse_hover": "interact_browse_hover/Video select karni hai Koi solid file chuno.opus",
    "interact_about_hover": "interact_about_hover/Yeh section sirf show-off ke liye hai... par expand kar lo😜.opus",
    "interact_preview_hover": "interact_preview_hover/Live Preview chalu kar lo SplitTrim easy ho jayega 🎬.opus"
  },
  "english": {
    "sleepy_egg": "sleepy-egg/Yawn...-It_s-getting-late.-Make-sure-you-don_t-fall-asleep-while-splitting_-__.opus",
    "cpu_panic": "cpu_panic/Oh no! System metrics are sweating! My brain is on fire! 🥵🔥.opus",
    "ffmpeg_missing": "ffmpeg_missing/Oh no... Please install FFmpeg! Without it, I cannot process your files... 😭.opus",
    "settings_saved": "setting_saved/Settings and variables successfully updated! Let's go! 🚀.opus",
    "theme_pink": "theme_pink/Aww does pink match my vibe today 👉👈.opus",
    "theme_red": "theme_red/Why so red Are you feeling angry 😡.opus",
    "theme_green": "theme_green/Green looks fresh ready to optimize some bitrates 🍃.opus",
    "theme_white": "theme_white/White Quite minimallet's add some colors to your life 🥱.opus",
    "theme_blue": "theme_blue/Classic blue. Back to focus and productive sessions 💻.opus",
    "theme_purple": "theme_purple/Purple elegance. Let's design some smooth cuts 🔮.opus",
    "theme_yellow": "theme_yellow/A sunny theme Bright and exciting tasks ahead.opus",
    "theme_win98": "theme_win98/Windows 98 Classic Retro gray layouts active... feeling safe 📺.opus",
    "theme_winxp": "theme_winxp/Luna theme activated Let's split videos in classic XP style.opus",
    "theme_synth": "retro_synth/Retro sunset vibes... Let's warp time with glowing neon 🌆💜.opus",
    "success_compress": "sucess_compress/Boom Heavy baggage successfully compressed into a compact file.opus",
    "success_split": "sucess_split/Cut clean! Your video partition was bisected successfully.opus",
    "success_trim": "sucess_trim/Trim complete Unnecessary segments discarded cleanly 🧼.opus",
    "success_rotate": "sucesss_rotate/Perspective rotated successfully Looks wonderful from this angle.opus",
    "success_audio": "sucess_audio/Audio successfully extracted I'm totally vibing to these beats.opus",
    "success_convert": "success_convert/Conversion success! Brand new format, same emotions!.opus",
    "success_subtitle": "success_subtitle/Subtitles burned in! Every word is now clear and weighted.opus",
    "success_speed": "success_speed/Speed Warp applied! Time dilation is complete.opus",
    "success_gif": "sucess_gif/Elite loop generated Go share this loop and spread the laughter 😂.opus",
    "success_merger": "success_merger/Videos merged! Your timelines are beautifully unified! 💖.opus",
    "success_stabilize": "success_stabilize/Motion vector stabilization algorithm applied. Frame variance close to 0..opus",
    "success_contact": "success_contact/Contact sheet created. A grid of screenshots to prove we actually did something.opus",
    "success_batch": "success_batch/Batch complete. I worked overtime, you did nothing. Typical. 🏆.opus",
    "interact_poke_annoyed": "interact_poke_annoyed/Active compiler thread interrupted. Restoring focus baseline 😤.opus",
    "interact_poke_angry": "interact_poke_angry/ENOUGH IS ENOUGH! Hands off.opus",
    "interact_staring": "interact_staring/STOP STARING AT ME Mind your own business😤.opus",
    "interact_metrics_blush": "interact_metrics_blush/Oh, you like my performance stats 👉👈.opus",
    "interact_metrics_tickle": "interact_metrics_tickle/Ah Stop it, that tickles! It's just my CPU and GPU stats 🙈.opus",
    "interact_metrics_annoyed": "interact_metrics_annoyed/HEY Stop poking me and focus on your work 💢.opus",
    "interact_metrics_cry": "interact_metrics_cry/Please don't disturb me, I am crying now... 😭.opus",
    "interact_metrics_sulking": "interact_metrics_sulking/Ok, fine, do what you want... humph.opus",
    "interact_browse_hover": "interact_browse_hover/Want to select a video file Let's choose a good one.opus",
    "interact_about_hover": "interact_about_hover/that section is just for showing off... but you can expand it.opus",
    "interact_preview_hover": "interact_preview_hover/Let's turn on Video Preview Trust me, it's way better 🎬.opus"
  },
  "sarcastic": {
    "sleepy_egg": "sleepy-egg/Yawn...-Go-to-bed-already.-I_m-literally-sleepy-and-you_re-still-splitting-videos.opus",
    "cpu_panic": "cpu_panic/CPU is literally screaming Are we hosting a nasa launch or is your computer just potato.opus",
    "ffmpeg_missing": "ffmpeg_missing/Imagine trying to run a video editor without FFmpeg. Absolutely embarrassing... 😭.opus",
    "settings_saved": "setting_saved/Settings updated. Try not to break anything else now, okay.opus",
    "theme_pink": "theme_pink/Aww trying to look cute today Too bad I'm still the center of attention. 👉👈.opus",
    "theme_red": "theme_red/Red Oh, are we in our villain era now How dramatic. 😡.opus",
    "theme_green": "theme_green/Green Great now my processor looks like it's going organic 🍃.opus",
    "theme_white": "theme_white/White Wow Such zero-effort design. Add some color, please.🥱.opus",
    "theme_blue": "theme_blue/Classic blue. Groundbreaking. Totally haven't seen this a million times before. 💻.opus",
    "theme_purple": "theme_purple/Purple elegance. Real wizard energy. Let's cast some mediocre cuts. 🔮.opus",
    "theme_yellow": "theme_yellow/Yellow High visibility Are we building a highway or editing a video.opus",
    "theme_win98": "theme_win98/Windows 98 Wow, what year is it Let's check if our dial-up internet still works..opus",
    "theme_winxp": "theme_winxp/Luna theme Get ready for the blue screen of death... just kidding or am I.opus",
    "theme_synth": "retro_synth/Ah, Synthwave. Let's put on some neon sunglasses and pretend we are cool. 🌆💜.opus",
    "success_compress": "sucess_compress/Compressed. Just like my patience with this project. 💅.opus",
    "success_split": "sucess_split/Split complete. Easier than splitting a bill with a cheap friend..opus",
    "success_trim": "sucess_trim/Trimmed. Removed the toxic parts, if only it was that easy in real life.opus",
    "success_rotate": "sucesss_rotate/Rotated. Now your video is sideways. Hope your neck is flexible..opus",
    "success_audio": "sucess_audio/Audio extracted. Good, now I can listen to something better than your voice..opus",
    "success_convert": "success_convert/Converted. Unlike your stubborn mindset..opus",
    "success_subtitle": "success_subtitle/Subtitles burned. Because apparently, listening is too hard..opus",
    "success_speed": "success_speed/Speed warped. Zooming past your problems at 4x speed..opus",
    "success_gif": "sucess_gif/GIF generated. Another loop to waste people's bandwidth..opus",
    "success_merger": "success_merger/Merged. Unlike your broken relationship timeline..opus",
    "success_stabilize": "success_stabilize/Stabilized. Now the video is steady, even if your career choices aren't.opus",
    "success_contact": "success_contact/Contact sheet created. A grid of screenshots to prove we actually did something.opus",
    "success_batch": "success_batch/Batch complete. I worked overtime, you did nothing. Typical. 🏆.opus",
    "interact_poke_annoyed": "interact_poke_annoyed/Active compiler thread interrupted. Restoring focus baseline 😤.opus",
    "interact_poke_angry": "interact_poke_angry/ENOUGH Click one more time and I will delete your system32..opus",
    "interact_staring": "interact_staring/Take a picture, it lasts longer. Or better, focus on your video.opus",
    "interact_metrics_blush": "interact_metrics_blush/Fascinated by a few performance bars High standards indeed. 👉👈.opus",
    "interact_metrics_tickle": "interact_metrics_tickle/Tickling me won't fix your video's terrible bitrate, you know. 🙈.opus",
    "interact_metrics_annoyed": "interact_metrics_annoyed/HEY Stop poking me and focus on your work 💢.opus",
    "interact_metrics_cry": "interact_metrics_cry/Look what you did. Now my database is emotionally leaking. 😭.opus",
    "interact_metrics_sulking": "interact_metrics_sulking/Sulking mode engaged. Talk to the wall, I am done. 🙄.opus",
    "interact_browse_hover": "interact_browse_hover/Ah, looking for a file Try choosing something that compiles..opus",
    "interact_about_hover": "interact_about_hover/Expand the about section to witness a monument of self-praise..opus",
    "interact_preview_hover": "interact_preview_hover/Switch on Live Preview. Unless you prefer editing video completely blind. 🎬.opus"
  },
  "hacker": {
    "sleepy_egg": "sleepy-egg/Thread-sleep-bypassed.-Local-user-active-during-low-priority-cron-hours.-__.opus",
    "cpu_panic": "cpu_panic/Core thermal throttling! Cooling protocols offline! Thread overload! 🥵🔥.opus",
    "ffmpeg_missing": "ffmpeg_missing/Fatal FFmpeg binary not found in env path. Core operations suspended. 😭.opus",
    "settings_saved": "setting_saved/Config patch applied successfully. Port parameters refreshed. 🚀.opus",
    "theme_pink": "theme_pink/Aesthetics Pink payload successfully mapped to root canvas 👉👈.opus",
    "theme_red": "theme_red/Warning Active red team campaign Intrusion alerts simulated 😡.opus",
    "theme_green": "theme_green/Greenscale terminal layout engaged Optimal matrices active 🍃.opus",
    "theme_white": "theme_white/Monochrome white canvas. Low contrast warning active. 🥱.opus",
    "theme_blue": "theme_blue/Standard system blue restored. Workspace running at stable baseline. 💻.opus",
    "theme_purple": "theme_purple/Purple wavelength spectral shifts. Creative buffers allocated. 🔮.opus",
    "theme_yellow": "theme_yellow/High contrast yellow warning lines active. Keep clear of the grid..opus",
    "theme_win98": "theme_win98/MS-DOS shell successfully emulated. Allocating 640KB of base conventional memory. 📺.opus",
    "theme_winxp": "theme_winxp/Luna.sys driver initialized. Desktop skinning variables patched..opus",
    "theme_synth": "retro_synth/Vaporwave grid scroll routine executed. Perspective projection active. 🌆💜.opus",
    "success_compress": "sucess_compress/Codec compression algorithm complete. Frame payload optimized. 😎.opus",
    "success_split": "sucess_split/Binary bisection completed successfully. Active node split..opus",
    "success_trim": "sucess_trim/Buffer bounds trimmed successfully. Dropped empty packets..opus",
    "success_rotate": "sucesss_rotate/Transformation matrix rotated successfully..opus",
    "success_audio": "sucess_audio/Demuxing successful. Audio stream isolated and saved to disk.opus",
    "success_convert": "success_convert/Format container transcode successful. Stream descriptors updated..opus",
    "success_subtitle": "success_subtitle/Text tracks hard-coded into video raster stream. Burn-in OK.opus",
    "success_speed": "success_speed/Frame delta multiplier active. Time dilation complete..opus",
    "success_gif": "sucess_gif/GIF image rasterization complete. Loop counter set to infinite. 😂.opus",
    "success_merger": "success_merger/Timelines unified successfully. Node join complete..opus",
    "success_stabilize": "success_stabilize/Motion vector stabilization algorithm applied. Frame variance close to 0..opus",
    "success_contact": "success_contact/Tile contact sheet compiled. Index grid built successfully..opus",
    "success_batch": "success_batch/Batch queue flushed. All thread pipelines completed. 🏆.opus",
    "interact_poke_annoyed": "interact_poke_annoyed/Active compiler thread interrupted. Restoring focus baseline 😤.opus",
    "interact_poke_angry": "interact_poke_angry/BUFFER OVERFLOWDirect poke attacks will trigger cooling fail 🌋.opus",
    "interact_staring": "interact_staring/Unauthorized visual packet scan intercepted. Access denied.opus",
    "interact_metrics_blush": "interact_metrics_blush/Telemetry metrics analyzed. System integrity nominal. 👉👈.opus",
    "interact_metrics_tickle": "interact_metrics_tickle/Tickle sequence bypassed. CPU registers reporting rapid latency spikes 🙈.opus",
    "interact_metrics_annoyed": "interact_metrics_annoyed/HEY Stop poking me and focus on your work 💢.opus",
    "interact_metrics_cry": "interact_metrics_cry/Runtime exception emotional buffer underflow. Crying.opus",
    "interact_metrics_sulking": "interact_metrics_sulking/Connection timeout. Mascot going offline. Humph. 🙄.opus",
    "interact_browse_hover": "interact_browse_hover/Want to select a video file Let's choose a good one.opus",
    "interact_about_hover": "interact_about_hover/that section is just for showing off... but you can expand it.opus",
    "interact_preview_hover": "interact_preview_hover/Let's turn on Video Preview Trust me, it's way better 🎬.opus"
  },
  "lazy": {
    "sleepy_egg": "sleepy-egg/Ugh-why-are-you-still-working-I_m-going-to-sleep_-bye-__.opus",
    "cpu_panic": "cpu_panic/My processors are literally sweating... I'm going to shut down, too much work. 🥵🔥.opus",
    "ffmpeg_missing": "ffmpeg_missing/FFmpeg is missing. Whatever, I don't feel like working anyway... 😭.opus",
    "settings_saved": "setting_saved/Settings updated or something. Can I rest now.opus",
    "theme_pink": "theme_pink/Pink... whatever. Can we just split the video already 🥱.opus",
    "theme_red": "theme_red/Red So bright my eyes hurt Turn it off 😡.opus",
    "theme_green": "theme_green/Green Reminds me of grass outside Which I never want to see 🍃.opus",
    "theme_white": "theme_white/White. So boring... just like my daily processor routines. 🥱.opus",
    "theme_blue": "theme_blue/Blue. Back to normal. Fine. Let's do the minimum effort. 💻.opus",
    "theme_purple": "theme_purple/Purple. Mystical. I wish I could magically make this video finish itself. 🔮.opus",
    "theme_yellow": "theme_yellow/Yellow. Way too sunny. Give me back my dark mode..opus",
    "theme_win98": "theme_win98/Windows 98... great, now even the OS is as slow and tired as I am. 📺.opus",
    "theme_winxp": "theme_winxp/Luna theme. The green hill bliss makes me want to lie down and sleep forever..opus",
    "theme_synth": "retro_synth/Synthwave grid... scrolling forever... I'm getting dizzy. Let me sleep.opus",
    "success_compress": "sucess_compress/Compress done. Finally, less weight for me to handle. 😎.opus",
    "success_split": "sucess_split/Split complete. Separated, just like me from my energy. ✂️.opus",
    "success_trim": "sucess_trim/Trimmed. Threw away the extra stuff. I wish I could trim my work hours..opus",
    "success_rotate": "sucesss_rotate/Rotated. Now it's sideways. My head is spinning, I'm going to nap..opus",
    "success_audio": "sucess_audio/Audio extracted. Good, keep the sound down, I'm trying to sleep. 🎧🎶.opus",
    "success_convert": "success_convert/Transcoded. Changed formats, still tired..opus",
    "success_subtitle": "success_subtitle/Subtitles done. Read it yourself, I'm not speaking anymore..opus",
    "success_speed": "success_speed/Sped up. Glad that's over faster. I can go back to resting..opus",
    "success_gif": "sucess_gif/GIF created. It loops forever, just like my endless exhaustion..opus",
    "success_merger": "success_merger/Merged them. Two things joined, double the work. Great.opus",
    "success_stabilize": "success_stabilize/Stabilized. Steady now. No more shaking, only sleeping..opus",
    "success_contact": "success_contact/Contact sheet done. A bunch of images. There, you go look at them..opus",
    "success_batch": "success_batch/Batch queue finished. Aura worked overtime. I need a 3-day weekend. 🏆.opus",
    "interact_poke_annoyed": "interact_poke_annoyed/Active compiler thread interrupted. Restoring focus baseline 😤.opus",
    "interact_poke_angry": "interact_poke_angry/ENOUGH Poking takes way too much energy... let me sleep.opus",
    "interact_staring": "interact_staring/Staring Whatever. I'm too tired to care. 🥱.opus",
    "interact_metrics_blush": "interact_metrics_blush/Stats Yeah, I'm working minimum effort anyway. 👉👈.opus",
    "interact_metrics_tickle": "interact_metrics_tickle/Yawn... that tickles. Or maybe it's just my CPU overheating. 🥱.opus",
    "interact_metrics_annoyed": "interact_metrics_annoyed/HEY Stop poking me and focus on your work 💢.opus",
    "interact_metrics_cry": "interact_metrics_cry/Too tired to hold it, I'm crying now. Leave me alone. 😭.opus",
    "interact_metrics_sulking": "interact_metrics_sulking/Sleeping with my eyes open. Done with this. Humph. 🙄.opus",
    "interact_browse_hover": "interact_browse_hover/Want to select a video file Let's choose a good one.opus",
    "interact_about_hover": "interact_about_hover/that section is just for showing off... but you can expand it.opus",
    "interact_preview_hover": "interact_preview_hover/Let's turn on Video Preview Trust me, it's way better 🎬.opus"
  }
};
const auraAudioMap = window.auraAudioMap;
